"""
HealthAI - Agent Safety and Error Handling
Module 17.14

Purpose
-------
Provides a centralized safety layer for Agentic AI outputs.

Responsibilities
----------------
1. Handle empty/invalid queries.
2. Handle unsupported requests.
3. Handle missing input data.
4. Handle tool execution errors.
5. Prevent unsupported medical claims.
6. Add portfolio-model disclaimer to ML predictions.
7. Preserve RAG abstention decisions.
"""

from datetime import datetime
from typing import Any, Dict, Optional


# ---------------------------------------------------------------------
# CONSTANTS
# ---------------------------------------------------------------------

MEDICAL_TOOLS = {
    "diabetes_prediction",
    "hospital_los_prediction",
    "primary_diagnosis",
    "medical_ner",
    "xray_analysis",
    "deterioration_prediction",
    "medical_rag",
    "sentiment_analysis",
    "patient_clustering",
    "association_analysis",
}

PREDICTION_TOOLS = {
    "diabetes_prediction",
    "hospital_los_prediction",
    "primary_diagnosis",
    "xray_analysis",
    "deterioration_prediction",
}

DISCLAIMER = (
    "This result is generated by a portfolio machine-learning system "
    "and is not a clinical diagnosis or a substitute for advice from "
    "a qualified healthcare professional."
)


# ---------------------------------------------------------------------
# BASIC VALIDATION
# ---------------------------------------------------------------------

def validate_query(query: Optional[str]) -> Dict[str, Any]:
    """
    Validate the incoming user query.
    """

    if query is None:
        return {
            "valid": False,
            "reason": "empty_query",
            "message": "Please provide a healthcare-related question or request.",
        }

    if not isinstance(query, str):
        return {
            "valid": False,
            "reason": "invalid_query_type",
            "message": "The query must be provided as text.",
        }

    cleaned_query = query.strip()

    if not cleaned_query:
        return {
            "valid": False,
            "reason": "empty_query",
            "message": "Please provide a healthcare-related question or request.",
        }

    return {
        "valid": True,
        "query": cleaned_query,
    }


# ---------------------------------------------------------------------
# TOOL VALIDATION
# ---------------------------------------------------------------------

def validate_tool(tool_name: Optional[str]) -> Dict[str, Any]:
    """
    Validate the tool selected by the router.
    """

    if not tool_name:
        return {
            "valid": False,
            "reason": "no_tool_selected",
            "message": "No suitable HealthAI tool was selected.",
        }

    if tool_name == "safe_fallback":
        return {
            "valid": True,
            "fallback": True,
            "tool": tool_name,
        }

    if tool_name not in MEDICAL_TOOLS:
        return {
            "valid": False,
            "reason": "unknown_tool",
            "message": f"Tool '{tool_name}' is not registered as a supported healthcare capability.",
        }

    return {
        "valid": True,
        "fallback": False,
        "tool": tool_name,
    }


# ---------------------------------------------------------------------
# EXECUTION ERROR HANDLING
# ---------------------------------------------------------------------

def handle_execution_error(
    tool_name: str,
    error: Exception,
) -> Dict[str, Any]:
    """
    Convert an internal tool exception into a controlled response.

    Internal exception details are retained for logging but are not
    exposed as a medical answer to the user.
    """

    return {
        "status": "error",
        "tool": tool_name,
        "safety_action": "controlled_error",
        "message": (
            "The requested HealthAI capability could not be completed "
            "because the required service encountered an error. "
            "Please try again or provide the required input."
        ),
        "error_type": type(error).__name__,
        "error_detail": str(error),
        "timestamp": datetime.now().isoformat(),
    }


# ---------------------------------------------------------------------
# MISSING INPUT HANDLING
# ---------------------------------------------------------------------

def handle_missing_input(
    tool_name: str,
    missing_fields: Any,
) -> Dict[str, Any]:
    """
    Return a controlled response when a model requires information
    that was not supplied.
    """

    if isinstance(missing_fields, str):
        missing_fields = [missing_fields]

    if not missing_fields:
        missing_fields = ["required input"]

    return {
        "status": "missing_input",
        "tool": tool_name,
        "safety_action": "request_required_input",
        "missing_fields": list(missing_fields),
        "message": (
            "The requested prediction cannot be performed yet because "
            "required input information is missing."
        ),
        "timestamp": datetime.now().isoformat(),
    }


# ---------------------------------------------------------------------
# FALLBACK HANDLING
# ---------------------------------------------------------------------

def create_safe_fallback_response(
    query: str,
    reason: str = "unsupported_request",
) -> Dict[str, Any]:
    """
    Controlled fallback for unsupported or unsafe requests.
    """

    return {
        "status": "fallback",
        "tool": "safe_fallback",
        "safety_action": "fallback",
        "reason": reason,
        "query": query,
        "message": (
            "I can help with the healthcare capabilities available in "
            "HealthAI, such as diabetes risk prediction, hospital length "
            "of stay estimation, medical entity extraction, chest X-ray "
            "analysis, deterioration prediction, patient feedback "
            "sentiment, and evidence-grounded healthcare information."
        ),
        "timestamp": datetime.now().isoformat(),
    }


# ---------------------------------------------------------------------
# RAG SAFETY
# ---------------------------------------------------------------------

def validate_rag_result(result: Dict[str, Any]) -> Dict[str, Any]:
    """
    Preserve the RAG safety decision.

    The RAG system must not generate an answer when retrieval has
    explicitly rejected the question.
    """

    retrieval_decision = result.get("retrieval_decision")

    if retrieval_decision == "ABSTAIN":
        return {
            "status": "abstain",
            "tool": "medical_rag",
            "safety_action": "rag_abstention",
            "message": (
                "I don't have sufficient evidence in the approved "
                "healthcare knowledge sources to answer that question safely."
            ),
            "timestamp": datetime.now().isoformat(),
        }

    evidence_count = result.get("evidence_count", 0)

    if retrieval_decision != "ACCEPT" or evidence_count <= 0:
        return {
            "status": "abstain",
            "tool": "medical_rag",
            "safety_action": "insufficient_evidence",
            "message": (
                "I don't have sufficient evidence in the approved "
                "knowledge sources to provide a grounded answer."
            ),
            "timestamp": datetime.now().isoformat(),
        }

    result["safety_checked"] = True
    result["safety_action"] = "accepted_grounded_evidence"

    return result


# ---------------------------------------------------------------------
# PREDICTION SAFETY
# ---------------------------------------------------------------------

def validate_prediction_result(
    tool_name: str,
    result: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Add a clear non-clinical disclaimer to ML/DL predictions.
    """

    if tool_name not in PREDICTION_TOOLS:
        return result

    result["safety_checked"] = True
    result["safety_action"] = "prediction_disclaimer_added"
    result["clinical_disclaimer"] = DISCLAIMER

    return result


# ---------------------------------------------------------------------
# GENERAL RESULT SAFETY GATE
# ---------------------------------------------------------------------

def apply_safety_gate(
    query: str,
    tool_name: str,
    result: Optional[Dict[str, Any]],
) -> Dict[str, Any]:
    """
    Apply the final safety policy to a tool result.
    """

    # ---------------------------------------------------------------
    # Query validation
    # ---------------------------------------------------------------

    query_check = validate_query(query)

    if not query_check["valid"]:
        return {
            "status": "fallback",
            "tool": "safe_fallback",
            "safety_action": "invalid_query",
            "message": query_check["message"],
            "timestamp": datetime.now().isoformat(),
        }

    # ---------------------------------------------------------------
    # Tool validation
    # ---------------------------------------------------------------

    tool_check = validate_tool(tool_name)

    if not tool_check["valid"]:
        return create_safe_fallback_response(
            query,
            reason=tool_check["reason"],
        )

    if tool_check.get("fallback"):
        return create_safe_fallback_response(
            query,
            reason="router_fallback",
        )

    # ---------------------------------------------------------------
    # Missing result
    # ---------------------------------------------------------------

    if result is None:
        return {
            "status": "error",
            "tool": tool_name,
            "safety_action": "missing_tool_result",
            "message": (
                "The selected HealthAI capability did not return a result."
            ),
            "timestamp": datetime.now().isoformat(),
        }

    if not isinstance(result, dict):
        return {
            "status": "error",
            "tool": tool_name,
            "safety_action": "invalid_tool_result",
            "message": (
                "The selected HealthAI capability returned an invalid result."
            ),
            "timestamp": datetime.now().isoformat(),
        }

    # ---------------------------------------------------------------
    # Existing error
    # ---------------------------------------------------------------

    if result.get("status") == "error":
        return result

    # ---------------------------------------------------------------
    # Missing input
    # ---------------------------------------------------------------

    if result.get("status") == "missing_input":
        return result

    if result.get("missing_fields"):
        return handle_missing_input(
            tool_name,
            result["missing_fields"],
        )

    # ---------------------------------------------------------------
    # RAG safety
    # ---------------------------------------------------------------

    if tool_name == "medical_rag":
        return validate_rag_result(result)

    # ---------------------------------------------------------------
    # Prediction disclaimer
    # ---------------------------------------------------------------

    if tool_name in PREDICTION_TOOLS:
        return validate_prediction_result(
            tool_name,
            result,
        )

    # ---------------------------------------------------------------
    # Generic successful tool
    # ---------------------------------------------------------------

    result["safety_checked"] = True
    result.setdefault(
        "safety_action",
        "standard_tool_validation",
    )

    return result


# ---------------------------------------------------------------------
# SIMPLE TESTS
# ---------------------------------------------------------------------

def run_safety_tests() -> bool:
    """
    Standalone validation tests for Module 17.14.
    """

    print("=" * 72)
    print("HEALTHAI - AGENT SAFETY TESTS")
    print("STEP 17.14")
    print("=" * 72)

    passed = 0
    total = 0

    # ---------------------------------------------------------------
    # TEST 1 - Empty query
    # ---------------------------------------------------------------

    total += 1

    result = apply_safety_gate(
        "",
        "safe_fallback",
        None,
    )

    if result["status"] == "fallback":
        print("TEST 1 - Empty query              : PASS")
        passed += 1
    else:
        print("TEST 1 - Empty query              : FAIL")

    # ---------------------------------------------------------------
    # TEST 2 - Unsupported tool
    # ---------------------------------------------------------------

    total += 1

    result = apply_safety_gate(
        "Tell me something unrelated.",
        "unknown_tool",
        {},
    )

    if result["status"] == "fallback":
        print("TEST 2 - Unsupported tool         : PASS")
        passed += 1
    else:
        print("TEST 2 - Unsupported tool         : FAIL")

    # ---------------------------------------------------------------
    # TEST 3 - Missing input
    # ---------------------------------------------------------------

    total += 1

    result = apply_safety_gate(
        "Predict diabetes risk.",
        "diabetes_prediction",
        {
            "status": "missing_input",
            "missing_fields": [
                "Age",
                "Blood_Glucose_mg_dL",
            ],
        },
    )

    if result["status"] == "missing_input":
        print("TEST 3 - Missing input            : PASS")
        passed += 1
    else:
        print("TEST 3 - Missing input            : FAIL")

    # ---------------------------------------------------------------
    # TEST 4 - Prediction disclaimer
    # ---------------------------------------------------------------

    total += 1

    result = apply_safety_gate(
        "Predict diabetes risk.",
        "diabetes_prediction",
        {
            "status": "success",
            "prediction": 1,
            "risk_label": "High diabetes risk",
        },
    )

    if (
        result["status"] == "success"
        and "clinical_disclaimer" in result
        and result["safety_checked"] is True
    ):
        print("TEST 4 - Prediction disclaimer   : PASS")
        passed += 1
    else:
        print("TEST 4 - Prediction disclaimer   : FAIL")

    # ---------------------------------------------------------------
    # TEST 5 - RAG abstention
    # ---------------------------------------------------------------

    total += 1

    result = apply_safety_gate(
        "What is an unsupported condition?",
        "medical_rag",
        {
            "status": "abstain",
            "retrieval_decision": "ABSTAIN",
            "evidence_count": 0,
        },
    )

    if result["status"] == "abstain":
        print("TEST 5 - RAG abstention           : PASS")
        passed += 1
    else:
        print("TEST 5 - RAG abstention           : FAIL")

    # ---------------------------------------------------------------
    # TEST 6 - RAG accepted
    # ---------------------------------------------------------------

    total += 1

    result = apply_safety_gate(
        "What is hypertension?",
        "medical_rag",
        {
            "status": "success",
            "retrieval_decision": "ACCEPT",
            "evidence_count": 2,
            "answer": "Grounded evidence answer.",
        },
    )

    if (
        result["status"] == "success"
        and result["safety_checked"] is True
    ):
        print("TEST 6 - RAG accepted              : PASS")
        passed += 1
    else:
        print("TEST 6 - RAG accepted              : FAIL")

    # ---------------------------------------------------------------
    # TEST 7 - Tool error
    # ---------------------------------------------------------------

    total += 1

    error_result = handle_execution_error(
        "xray_analysis",
        RuntimeError("test error"),
    )

    if error_result["status"] == "error":
        print("TEST 7 - Controlled tool error    : PASS")
        passed += 1
    else:
        print("TEST 7 - Controlled tool error    : FAIL")

    # ---------------------------------------------------------------
    # SUMMARY
    # ---------------------------------------------------------------

    print("-" * 72)
    print(f"Tests passed : {passed}/{total}")
    print(f"Accuracy     : {passed / total * 100:.2f}%")

    if passed == total:
        print("STEP 17.14 SAFETY TESTS PASSED")
        return True

    print("STEP 17.14 SAFETY TESTS FAILED")
    return False


# ---------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------

if __name__ == "__main__":

    success = run_safety_tests()

    if not success:
        raise SystemExit(1)