"""
HealthAI - Agentic AI Explainability & Error Analysis
Module 17.15

Purpose
-------
Create a centralized explainability and error-analysis report for
the HealthAI Agentic AI layer.

This module does NOT retrain models.

It consolidates the explainability evidence already produced by the
individual HealthAI modules and verifies the corresponding artifacts.

Explainability methods represented:
    - Diabetes prediction       : feature/model evaluation
    - Hospital LOS              : XGBoost feature importance + SHAP
    - Patient clustering        : cluster centers + profiles
    - Association analysis      : support/confidence/lift
    - Chest X-ray CNN           : Grad-CAM
    - Deterioration RNN         : permutation importance
    - Medical NER               : per-entity evaluation
    - Sentiment                 : error analysis
    - Medical RAG               : retrieval/safety evaluation
    - Primary diagnosis         : classification evaluation

Output:
    data/processed/agentic_ai/agent_explainability_report.json
"""

from pathlib import Path
import json
from datetime import datetime


# =====================================================================
# PROJECT PATHS
# =====================================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]

DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"
MODELS = PROJECT_ROOT / "models"


OUTPUT_DIR = DATA_PROCESSED / "agentic_ai"

OUTPUT_FILE = OUTPUT_DIR / "agent_explainability_report.json"


# =====================================================================
# HELPER FUNCTIONS
# =====================================================================

def artifact_status(paths):
    """
    Check whether one or more expected artifacts exist.
    """

    if isinstance(paths, (str, Path)):
        paths = [paths]

    existing = []
    missing = []

    for path in paths:

        path = Path(path)

        if path.exists():
            existing.append(str(path.relative_to(PROJECT_ROOT)))
        else:
            missing.append(str(path.relative_to(PROJECT_ROOT)))

    return {
        "available": len(existing) > 0,
        "existing_artifacts": existing,
        "missing_artifacts": missing,
    }


def create_tool_entry(
    tool_name,
    task,
    explainability_method,
    interpretation,
    limitations,
    artifacts,
):
    """
    Create a standardized explainability entry.
    """

    status = artifact_status(artifacts)

    return {
        "tool": tool_name,
        "task": task,
        "explainability_method": explainability_method,
        "interpretation": interpretation,
        "limitations": limitations,
        "artifact_status": status,
    }


# =====================================================================
# BUILD EXPLAINABILITY REPORT
# =====================================================================

def build_explainability_report():

    print("=" * 72)
    print("HEALTHAI - AGENTIC AI EXPLAINABILITY")
    print("STEP 17.15")
    print("=" * 72)

    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    report = {
        "project": "HealthAI-Intelligent-Platform",
        "module": "17_agentic_ai",
        "step": "17.15",
        "report_type": "centralized_explainability_and_error_analysis",
        "generated_at": datetime.now().isoformat(),
        "tools": {},
    }


    # =================================================================
    # 1. DIABETES PREDICTION
    # =================================================================

    print("\n[1/9] Diabetes prediction explainability")

    diabetes_artifacts = [
        MODELS
        / "classical_ml"
        / "diabetes_prediction"
        / "diabetes_prediction_model.joblib",

        MODELS
        / "classical_ml"
        / "diabetes_prediction"
        / "metadata.json",

        MODELS
        / "classical_ml"
        / "diabetes_prediction"
        / "test_predictions.csv",
    ]

    report["tools"]["diabetes_prediction"] = create_tool_entry(
        tool_name="diabetes_prediction",
        task="Binary diabetes risk prediction",
        explainability_method=[
            "model evaluation metrics",
            "classification report",
            "test-set predictions",
            "model metadata",
        ],
        interpretation=(
            "The model output represents estimated diabetes risk from "
            "the portfolio model. Test predictions and classification "
            "metrics provide performance evidence."
        ),
        limitations=(
            "Feature importance or SHAP attribution is not claimed here "
            "unless explicitly generated by a separate analysis artifact."
        ),
        artifacts=diabetes_artifacts,
    )

    print("    Completed")


    # =================================================================
    # 2. HOSPITAL LOS
    # =================================================================

    print("[2/9] Hospital LOS explainability")

    los_artifacts = [
        MODELS
        / "classical_ml"
        / "hospital_los"
        / "hospital_los_model.joblib",

        MODELS
        / "classical_ml"
        / "hospital_los"
        / "metadata.json",

        DATA_PROCESSED
        / "length_of_stay"
        / "hospital_los_test_predictions.csv",

        DATA_PROCESSED
        / "length_of_stay"
        / "regression_model_comparison.csv",
    ]

    report["tools"]["hospital_los_prediction"] = create_tool_entry(
        tool_name="hospital_los_prediction",
        task="Hospital length-of-stay regression",
        explainability_method=[
            "XGBoost feature importance",
            "SHAP analysis",
            "model comparison",
            "test-set predictions",
        ],
        interpretation=(
            "XGBoost feature importance and SHAP analysis provide "
            "model-level evidence about which input variables influence "
            "length-of-stay predictions."
        ),
        limitations=(
            "Feature importance describes model behavior and should not "
            "be interpreted as clinical causality."
        ),
        artifacts=los_artifacts,
    )

    print("    Completed")


    # =================================================================
    # 3. PATIENT CLUSTERING
    # =================================================================

    print("[3/9] Patient clustering explainability")

    clustering_artifacts = [
        DATA_PROCESSED
        / "patient_segmentation"
        / "clustering_results"
        / "patient_clusters.csv",

        DATA_PROCESSED
        / "patient_segmentation"
        / "clustering_results"
        / "cluster_distribution.csv",

        DATA_PROCESSED
        / "patient_segmentation"
        / "clustering_results"
        / "cluster_centers.csv",

        DATA_PROCESSED
        / "patient_segmentation"
        / "final_results"
        / "final_cluster_summary.csv",
    ]

    report["tools"]["patient_clustering"] = create_tool_entry(
        tool_name="patient_clustering",
        task="Patient segmentation using K-Means clustering",
        explainability_method=[
            "cluster centers",
            "cluster distribution",
            "cluster profiling",
            "final cluster summary",
        ],
        interpretation=(
            "Cluster centers and patient profiles describe the "
            "characteristics of each discovered patient segment."
        ),
        limitations=(
            "Clusters are unsupervised groupings and should not be "
            "interpreted as clinical diagnoses or causal patient groups."
        ),
        artifacts=clustering_artifacts,
    )

    print("    Completed")


    # =================================================================
    # 4. ASSOCIATION ANALYSIS
    # =================================================================

    print("[4/9] Association analysis explainability")

    association_artifacts = [
        DATA_PROCESSED
        / "associative_learning"
        / "meaningful_association_rules.csv",

        DATA_PROCESSED
        / "associative_learning"
        / "rule_filtering_summary.csv",

        DATA_PROCESSED
        / "associative_learning"
        / "clinical_association_rules.csv",

        DATA_PROCESSED
        / "associative_learning"
        / "clinical_association_summary.csv",
    ]

    report["tools"]["association_analysis"] = create_tool_entry(
        tool_name="association_analysis",
        task="Clinical association rule mining",
        explainability_method=[
            "support",
            "confidence",
            "lift",
            "filtered clinical association rules",
        ],
        interpretation=(
            "Association rules expose relationships between frequently "
            "co-occurring clinical attributes. Support measures frequency, "
            "confidence measures conditional occurrence, and lift measures "
            "association strength relative to independent occurrence."
        ),
        limitations=(
            "Association does not establish causation. Rules represent "
            "patterns in the analyzed dataset."
        ),
        artifacts=association_artifacts,
    )

    print("    Completed")


    # =================================================================
    # 5. CHEST X-RAY CNN
    # =================================================================

    print("[5/9] Chest X-ray CNN explainability")

    cnn_artifacts = [
        DATA_PROCESSED
        / "deep_learning"
        / "cnn"
        / "cnn_model.keras",

        DATA_PROCESSED
        / "deep_learning"
        / "cnn"
        / "xray_gradcam_explanation.png",

        DATA_PROCESSED
        / "deep_learning"
        / "cnn"
        / "xray_gradcam_heatmap.png",
    ]

    report["tools"]["xray_analysis"] = create_tool_entry(
        tool_name="xray_analysis",
        task="Chest X-ray pneumonia classification",
        explainability_method=[
            "Grad-CAM",
            "CNN performance metrics",
            "prediction probability",
        ],
        interpretation=(
            "Grad-CAM provides a visual indication of image regions "
            "that contributed to the CNN prediction."
        ),
        limitations=(
            "Grad-CAM is an explanation of model attention and is not "
            "proof that a highlighted region represents a disease."
        ),
        artifacts=cnn_artifacts,
    )

    print("    Completed")


    # =================================================================
    # 6. DETERIORATION RNN
    # =================================================================

    print("[6/9] Patient deterioration explainability")

    rnn_artifacts = [
        DATA_PROCESSED
        / "deep_learning"
        / "rnn"
        / "rnn_model.keras",
    ]

    report["tools"]["deterioration_prediction"] = create_tool_entry(
        tool_name="deterioration_prediction",
        task="Patient deterioration prediction from temporal sequences",
        explainability_method=[
            "permutation importance",
            "RNN/LSTM performance comparison",
            "ROC-AUC",
            "precision",
            "recall",
            "F1 score",
        ],
        interpretation=(
            "Permutation importance measures the change in model "
            "performance when individual input features are shuffled. "
            "The temporal model comparison provides additional evidence "
            "for model selection."
        ),
        limitations=(
            "Permutation importance reflects predictive contribution "
            "to the trained model and should not be interpreted as "
            "causal clinical importance."
        ),
        artifacts=rnn_artifacts,
    )

    print("    Completed")


    # =================================================================
    # 7. MEDICAL NER
    # =================================================================

    print("[7/9] Medical NER explainability")

    ner_artifacts = [
        MODELS
        / "nlp"
        / "biobert_ner",

        MODELS
        / "nlp"
        / "clinicalbert_ner",

        DATA_PROCESSED
        / "agentic_ai"
        / "medical_ner_adapter_test.json",
    ]

    report["tools"]["medical_ner"] = create_tool_entry(
        tool_name="medical_ner",
        task="Medical named entity recognition",
        explainability_method=[
            "entity-level precision",
            "entity-level recall",
            "entity-level F1",
            "per-entity-category evaluation",
            "BioBERT vs ClinicalBERT comparison",
        ],
        interpretation=(
            "Per-entity evaluation shows how well the NER models "
            "recognize individual medical entity categories."
        ),
        limitations=(
            "Performance varies across entity categories. The selected "
            "BioBERT model is a portfolio NLP model and is not a clinically "
            "validated information extraction system."
        ),
        artifacts=ner_artifacts,
    )

    print("    Completed")


    # =================================================================
    # 8. SENTIMENT ANALYSIS
    # =================================================================

    print("[8/9] Medical sentiment explainability")

    sentiment_artifacts = [
        MODELS
        / "nlp"
        / "sentiment"
        / "tfidf_logistic_regression"
        / "tfidf_vectorizer.pkl",

        MODELS
        / "nlp"
        / "sentiment"
        / "tfidf_logistic_regression"
        / "logistic_regression_model.pkl",
    ]

    report["tools"]["sentiment_analysis"] = create_tool_entry(
        tool_name="sentiment_analysis",
        task="Patient feedback sentiment classification",
        explainability_method=[
            "TF-IDF representation",
            "classification metrics",
            "confusion matrix",
            "error analysis",
            "TF-IDF vs DistilBERT comparison",
        ],
        interpretation=(
            "The baseline uses TF-IDF text representations with logistic "
            "regression. Error analysis identifies examples where the "
            "classifier makes incorrect predictions."
        ),
        limitations=(
            "The evaluation dataset contains only 20 unique feedback "
            "texts with substantial duplication. Therefore the reported "
            "sentiment performance is illustrative and requires a larger "
            "diverse labeled dataset for production use."
        ),
        artifacts=sentiment_artifacts,
    )

    print("    Completed")


    # =================================================================
    # 9. MEDICAL RAG
    # =================================================================

    print("[9/9] Medical RAG explainability")

    rag_artifacts = [
        DATA_PROCESSED
        / "rag"
        / "context"
        / "rag_safety_aware_contexts.json",
    ]

    report["tools"]["medical_rag"] = create_tool_entry(
        tool_name="medical_rag",
        task="Evidence-grounded healthcare question answering",
        explainability_method=[
            "retrieved evidence chunks",
            "semantic relevance score",
            "topic matching",
            "safety threshold",
            "RAG abstention",
            "clean extractive grounded answering",
        ],
        interpretation=(
            "RAG explanations are grounded in retrieved healthcare "
            "source passages. The safety layer can abstain when sufficient "
            "evidence is not available."
        ),
        limitations=(
            "The current evaluation uses a limited set of authoritative "
            "sources and a controlled evaluation question set. It is "
            "not a clinically validated medical decision-support system."
        ),
        artifacts=rag_artifacts,
    )

    print("    Completed")


    # =================================================================
    # PRIMARY DIAGNOSIS
    # =================================================================

    print("\n[Additional] Primary diagnosis classification")

    primary_diagnosis_artifacts = [
        MODELS
        / "classical_ml"
        / "primary_diagnosis"
        / "primary_diagnosis_model.joblib",

        MODELS
        / "classical_ml"
        / "primary_diagnosis"
        / "primary_diagnosis_preprocessor.joblib",

        MODELS
        / "classical_ml"
        / "primary_diagnosis"
        / "primary_diagnosis_label_encoder.joblib",

        MODELS
        / "classical_ml"
        / "primary_diagnosis"
        / "metadata.json",
    ]

    report["tools"]["primary_diagnosis"] = create_tool_entry(
        tool_name="primary_diagnosis",
        task="Primary diagnosis classification",
        explainability_method=[
            "classification accuracy",
            "macro precision",
            "macro recall",
            "macro F1",
            "weighted F1",
            "Random Forest vs XGBoost comparison",
        ],
        interpretation=(
            "The selected Random Forest model was chosen based on the "
            "evaluated classification metrics and model comparison."
        ),
        limitations=(
            "The model is a portfolio classification model and should "
            "not be treated as a clinical diagnostic system."
        ),
        artifacts=primary_diagnosis_artifacts,
    )

    # =================================================================
    # GLOBAL SUMMARY
    # =================================================================

    total_tools = len(report["tools"])

    tools_with_artifacts = sum(
        1
        for tool in report["tools"].values()
        if tool["artifact_status"]["available"]
    )

    report["summary"] = {
        "total_tools_documented": total_tools,
        "tools_with_artifacts": tools_with_artifacts,
        "tools_without_any_expected_artifact": (
            total_tools - tools_with_artifacts
        ),
        "explainability_principle": (
            "HealthAI reports only explainability evidence that has "
            "actually been produced by the corresponding model or "
            "analysis pipeline."
        ),
        "clinical_safety_principle": (
            "Model explanations are intended to describe model behavior "
            "and evidence, not establish clinical causality or diagnosis."
        ),
    }

    # =================================================================
    # SAVE
    # =================================================================

    with open(
        OUTPUT_FILE,
        "w",
        encoding="utf-8",
    ) as f:

        json.dump(
            report,
            f,
            indent=4,
        )

    print("\n" + "-" * 72)
    print("Explainability report saved:")
    print(OUTPUT_FILE)

    print("\nTool coverage:")

    for tool_name, tool_info in report["tools"].items():

        available = tool_info["artifact_status"]["available"]

        status = "AVAILABLE" if available else "CHECK"

        print(
            f"{tool_name:30s}: {status}"
        )

    print("\n" + "-" * 72)

    print(
        f"Tools documented       : {total_tools}"
    )

    print(
        f"With artifacts         : {tools_with_artifacts}"
    )

    print(
        f"Without artifacts      : "
        f"{total_tools - tools_with_artifacts}"
    )

    print("\nSTEP 17.15 EXPLAINABILITY REPORT CREATED")

    return report


# =====================================================================
# MAIN
# =====================================================================

if __name__ == "__main__":

    build_explainability_report()