"""
HealthAI - Patient Clustering Agent Adapter

Purpose:
    Connect the existing Module 14 patient segmentation
    results to the Agentic AI layer.

Important:
    This adapter uses the already-generated clustering results.
    It does NOT retrain K-Means and does NOT dynamically assign
    a new patient to a cluster.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pandas as pd


# ============================================================
# PROJECT PATHS
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]

CLUSTER_RESULTS_DIR = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "patient_segmentation"
    / "clustering_results"
)

FINAL_RESULTS_DIR = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "patient_segmentation"
    / "final_results"
)

PATIENT_CLUSTERS_PATH = (
    CLUSTER_RESULTS_DIR / "patient_clusters.csv"
)

CLUSTER_DISTRIBUTION_PATH = (
    CLUSTER_RESULTS_DIR / "cluster_distribution.csv"
)

FINAL_CLUSTER_SUMMARY_PATH = (
    FINAL_RESULTS_DIR / "final_cluster_summary.csv"
)


# ============================================================
# LOAD EXISTING CLUSTERING RESULTS
# ============================================================

def load_clustering_results() -> dict[str, pd.DataFrame]:
    """Load the clustering outputs generated by Module 14."""

    required_files = {
        "patient_clusters": PATIENT_CLUSTERS_PATH,
        "cluster_distribution": CLUSTER_DISTRIBUTION_PATH,
        "final_cluster_summary": FINAL_CLUSTER_SUMMARY_PATH,
    }

    for name, path in required_files.items():
        if not path.exists():
            raise FileNotFoundError(
                f"Required clustering file '{name}' was not found:\n"
                f"{path}"
            )

    return {
        "patient_clusters": pd.read_csv(
            PATIENT_CLUSTERS_PATH
        ),
        "cluster_distribution": pd.read_csv(
            CLUSTER_DISTRIBUTION_PATH
        ),
        "final_cluster_summary": pd.read_csv(
            FINAL_CLUSTER_SUMMARY_PATH
        ),
    }


# ============================================================
# BUILD CLUSTER SUMMARY
# ============================================================

def build_cluster_summary(
    summary_df: pd.DataFrame,
) -> list[dict[str, Any]]:
    """Convert cluster summary DataFrame into API/agent-friendly data."""

    results: list[dict[str, Any]] = []

    for _, row in summary_df.iterrows():

        results.append(
            {
                "cluster": int(row["Cluster"]),
                "patient_count": int(row["Patient_Count"]),
                "percentage": round(
                    float(row["Percentage"]),
                    3,
                ),
                "average_age": round(
                    float(row["Age"]),
                    2,
                ),
                "average_blood_glucose_mg_dL": round(
                    float(row["Blood_Glucose_mg_dL"]),
                    2,
                ),
                "average_hba1c_percent": round(
                    float(row["HbA1c_%"]),
                    2,
                ),
                "average_total_cholesterol_mg_dL": round(
                    float(row["Total_Cholesterol_mg_dL"]),
                    2,
                ),
                "average_bmi": round(
                    float(row["BMI"]),
                    2,
                ),
                "type2_diabetes_percentage": round(
                    float(row["Type2_Diabetes_Percentage"]),
                    2,
                ),
            }
        )

    return results


# ============================================================
# BUILD DISTRIBUTION
# ============================================================

def build_cluster_distribution(
    distribution_df: pd.DataFrame,
) -> list[dict[str, Any]]:
    """Convert cluster distribution into agent-friendly data."""

    results: list[dict[str, Any]] = []

    for _, row in distribution_df.iterrows():

        results.append(
            {
                "cluster": int(row["Cluster"]),
                "patient_count": int(row["Patient_Count"]),
                "percentage": round(
                    float(row["Percentage"]),
                    3,
                ),
            }
        )

    return results


# ============================================================
# MAIN AGENT TOOL FUNCTION
# ============================================================

def execute_patient_clustering(
    query: str = "",
    **kwargs: Any,
) -> dict[str, Any]:
    """
    Execute the patient clustering agent tool.

    This reports the existing Module 14 clustering analysis.
    """

    try:

        data = load_clustering_results()

        summary_df = data["final_cluster_summary"]

        distribution_df = data["cluster_distribution"]

        cluster_summary = build_cluster_summary(
            summary_df
        )

        cluster_distribution = build_cluster_distribution(
            distribution_df
        )

        return {
            "status": "success",

            "tool": "patient_clustering",

            "prediction_type": "patient_clustering",

            "query": query,

            "analysis_type": "K-Means patient segmentation",

            "cluster_count": int(
                summary_df["Cluster"].nunique()
            ),

            "total_patients": int(
                summary_df["Patient_Count"].sum()
            ),

            "cluster_distribution": cluster_distribution,

            "cluster_summary": cluster_summary,

            "source": (
                "Module 14 patient segmentation "
                "precomputed clustering results"
            ),

            "model_status": (
                "Precomputed clustering analysis"
            ),

            "note": (
                "This agent tool reports existing "
                "patient segmentation results. "
                "It does not retrain K-Means or "
                "dynamically assign new patients "
                "to clusters."
            ),
        }

    except Exception as exc:

        return {
            "status": "error",

            "tool": "patient_clustering",

            "prediction_type": "patient_clustering",

            "query": query,

            "message": (
                "Patient clustering execution failed."
            ),

            "error": str(exc),
        }


# ============================================================
# STANDALONE TEST
# ============================================================

def main() -> None:

    print("=" * 70)
    print("HEALTHAI - PATIENT CLUSTERING AGENT ADAPTER")
    print("=" * 70)

    print("\nChecking Module 14 result files...")

    print(
        "Patient clusters     :",
        "AVAILABLE"
        if PATIENT_CLUSTERS_PATH.exists()
        else "MISSING",
    )

    print(
        "Cluster distribution :",
        "AVAILABLE"
        if CLUSTER_DISTRIBUTION_PATH.exists()
        else "MISSING",
    )

    print(
        "Final cluster summary:",
        "AVAILABLE"
        if FINAL_CLUSTER_SUMMARY_PATH.exists()
        else "MISSING",
    )

    print("\nRunning adapter test...")

    result = execute_patient_clustering(
        query="Show me the patient clusters."
    )

    print("\nAdapter status:")
    print(result.get("status"))

    if result.get("status") == "success":

        print(
            "\nAnalysis type:",
            result["analysis_type"],
        )

        print(
            "Number of clusters:",
            result["cluster_count"],
        )

        print(
            "Total patients:",
            result["total_patients"],
        )

        print("\nCluster distribution:")

        for cluster in result["cluster_distribution"]:
            print(
                f"  Cluster {cluster['cluster']}: "
                f"{cluster['patient_count']} patients "
                f"({cluster['percentage']}%)"
            )

        print("\nCluster summary:")

        for cluster in result["cluster_summary"]:

            print(
                f"  Cluster {cluster['cluster']} | "
                f"Age={cluster['average_age']} | "
                f"Glucose={cluster['average_blood_glucose_mg_dL']} | "
                f"HbA1c={cluster['average_hba1c_percent']} | "
                f"BMI={cluster['average_bmi']} | "
                f"Type2 Diabetes="
                f"{cluster['type2_diabetes_percentage']}%"
            )

        print(
            "\nSTEP - PATIENT CLUSTERING "
            "ADAPTER TEST PASSED"
        )

    else:

        print(
            "\nSTEP - PATIENT CLUSTERING "
            "ADAPTER TEST FAILED"
        )

        print(
            "Error:",
            result.get("error"),
        )


if __name__ == "__main__":
    main()